<a href="https://colab.research.google.com/github/ankit-kandari/NLP-TMBD-movie-reviews-text-preparation/blob/main/tmbd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import requests

In [ ]:
url = "https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1"
response = requests.get(url)

In [ ]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
   'popularity': 119.766,
   'poster_path': '/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
   'release_date': '1994-09-23',
   'title': 'The Shawshank Redemption',
   'video': False,
   'vote_average': 8.712,
   'vote_count': 25525},
  {'adult': False,
   'backdrop_path': '/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 105.608,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'title': 'The Godfather',
   'video': False,
   'vote_average': 8.707,
   'vote_count': 19420},
  {'adult': False,
   'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
   'genre_ids': [18, 80],
   'id': 240,
   'original_language': 'en',
   'original_title': 'The Godfather Part II',
   'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
   'popularity': 86.122,
   'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
   'release_date': '1974-12-20',
   'title': 'The Godfather Part II',
   'video': False,
   'vote_average': 8.591,
   'vote_count': 11712},
  {'adult': False,
   'backdrop_path': '/3f92DMBTFqr3wgXpfxzrb0qv8nG.jpg',
   'genre_ids': [18, 36, 10752],
   'id': 424,
   'original_language': 'en',
   'original_title': "Schindler's List",
   'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
   'popularity': 72.147,
   'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
   'release_date': '1993-12-15',
   'title': "Schindler's List",
   'video': False,
   'vote_average': 8.572,
   'vote_count': 15094},
  {'adult': False,
   'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
   'genre_ids': [18],
   'id': 389,
   'original_language': 'en',
   'original_title': '12 Angry Men',
   'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
   'popularity': 47.243,
   'poster_path': '/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
   'release_date': '1957-04-10',
   'title': '12 Angry Men',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 8016},
  {'adult': False,
   'backdrop_path': '/mSDsSDwaP3E7dEfUPWy4J0djt4O.jpg',
   'genre_ids': [16, 10751, 14],
   'id': 129,
   'original_language': 'ja',
   'original_title': '千と千尋の神隠し',
   'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
   'popularity': 95.967,
   'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
   'release_date': '2001-07-20',
   'title': 'Spirited Away',
   'video': False,
   'vote_average': 8.54,
   'vote_count': 15504},
  {'adult': False,
   'backdrop_path': '/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 19404,
   'original_language': 'hi',
   'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
   'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
   'popularity': 37.447,
   'poster_path': '/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg',
   'release_date': '1995-10-20',
   'title': 'Dilwale Dulhania Le Jayenge',
   'video': False,
   'vote_average': 8.539,
   'vote_count': 4333},
  {'adult': False,
   'backdrop_path': '/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
   'genre_ids': [18, 28, 80, 53],
   'id': 155,
   'original_language': 'en',
   'original_title': 'The Dark Knight',
   'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
   'popularity': 117.198,
   'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
   'release_date': '2008-07-16',
   'title': 'The Dark Knight',
   'video': False,
   'vote_average': 8.515,
   'vote_count': 31429},
  {'adult': False,
   'backdrop_path': '/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
   'genre_ids': [35, 53, 18],
   'id': 496243,
   'original_language': 'ko',
   'original_title': '기생충',
   'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
   'popularity': 94.043,
   'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
   'release_date': '2019-05-30',
   'title': 'Parasite',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 17070},
  {'adult': False,
   'backdrop_path': '/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg',
   'genre_ids': [14, 18, 80],
   'id': 497,
   'original_language': 'en',
   'original_title': 'The Green Mile',
   'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
   'popularity': 77.179,
   'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
   'release_date': '1999-12-10',
   'title': 'The Green Mile',
   'video': False,
   'vote_average': 8.511,
   'vote_count': 16458},
  {'adult': False,
   'backdrop_path': '/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg',
   'genre_ids': [10749, 16, 18],
   'id': 372058,
   'original_language': 'ja',
   'original_title': '君の名は。',
   'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
   'popularity': 80.19,
   'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
   'release_date': '2016-08-26',
   'title': 'Your Name.',
   'video': False,
   'vote_average': 8.497,
   'vote_count': 10740},
  {'adult': False,
   'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
   'genre_ids': [53, 80],
   'id': 680,
   'original_language': 'en',
   'original_title': 'Pulp Fiction',
   'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
   'popularity': 90.812,
   'poster_path': '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
   'release_date': '1994-09-10',
   'title': 'Pulp Fiction',
   'video': False,
   'vote_average': 8.489,
   'vote_count': 26622},
  {'adult': False,
   'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
   'genre_ids': [12, 14, 28],
   'id': 122,
   'original_language': 'en',
   'original_title': 'The Lord of the Rings: The Return of the King',
   'overview': "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
   'popularity': 101.646,
   'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
   'release_date': '2003-12-01',
   'title': 'The Lord of the Rings: The Return of the King',
   'video': False,
   'vote_average': 8.477,
   'vote_count': 23001},
  {'adult': False,
   'backdrop_path': '/qdIMHd4sEfJSckfVJfKQvisL02a.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 13,
   'original_language': 'en',
   'original_title': 'Forrest Gump',
   'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
   'popularity': 97.739,
   'poster_path': '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
   'release_date': '1994-06-23',
   'title': 'Forrest Gump',
   'video': False,
   'vote_average': 8.477,
   'vote_count': 26144},
  {'adult': False,
   'backdrop_path': '/x4biAVdPVCghBlsVIzB6NmbghIz.jpg',
   'genre_ids': [37],
   'id': 429,
   'original_language': 'it',
   'original_title': 'Il buono, il brutto, il cattivo',
   'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
   'popularity': 63.73,
   'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
   'release_date': '1966-12-22',
   'title': 'The Good, the Bad and the Ugly',
   'video': False,
   'vote_average': 8.467,
   'vote_count': 8070},
  {'adult': False,
   'backdrop_path': '/sw7mordbZxgITU877yTpZCud90M.jpg',
   'genre_ids': [18, 80],
   'id': 769,
   'original_language': 'en',
   'original_title': 'GoodFellas',
   'overview': 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
   'popularity': 62.104,
   'poster_path': '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
   'release_date': '1990-09-12',
   'title': 'GoodFellas',
   'video': False,
   'vote_average': 8.467,
   'vote_count': 12139},
  {'adult': False,
   'backdrop_path': '/dlC0ed9Ugh3FzydnkBtV5lRXUu4.jpg',
   'genre_ids': [16, 18, 10752],
   'id': 12477,
   'original_language': 'ja',
   'original_title': '火垂るの墓',
   'overview': 'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.',
   'popularity': 0.6,
   'poster_path': '/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg',
   'release_date': '1988-04-16',
   'title': 'Grave of the Fireflies',
   'video': False,
   'vote_average': 8.458,
   'vote_count': 5095},
  {'adult': False,
   'backdrop_path': '/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg',
   'genre_ids': [35, 18],
   'id': 637,
   'original_language': 'it',
   'original_title': 'La vita è bella',
   'overview': 'A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.',
   'popularity': 40.453,
   'poster_path': '/6tEJnof1DKWPnl5lzkjf0FVv7oB.jpg',
   'release_date': '1997-12-20',
   'title': 'Life Is Beautiful',
   'video': False,
   'vote_average': 8.455,
   'vote_count': 12555},
  {'adult': False,
   'backdrop_path': '/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg',
   'genre_ids': [28, 18],
   'id': 346,
   'original_language': 'ja',
   'original_title': '七人の侍',
   'overview': "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
   'popularity': 42.318,
   'poster_path': '/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg',
   'release_date': '1954-04-26',
   'title': 'Seven Samurai',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 3393},
  {'adult': False,
   'backdrop_path': '/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg',
   'genre_ids': [18, 10749],
   'id': 11216,
   'original_language': 'it',
   'original_title': 'Nuovo Cinema Paradiso',
   'overview': "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
   'popularity': 30.838,
   'poster_path': '/8SRUfRUi6x4O68n0VCbDNRa6iGL.jpg',
   'release_date': '1988-11-17',
   'title': 'Cinema Paradiso',
   'video': False,
   'vote_average': 8.452,
   'vote_count': 4112}],
 'total_pages': 458,
 'total_results': 9158}

In [ ]:
pd.DataFrame(response.json()["results"])[["id","original_language","original_title","release_date","title","popularity","overview"]]

,id,original_language,original_title,release_date,title,popularity,overview
0,278,en,The Shawshank Redemption,1994-09-23,The Shawshank Redemption,119.766,Framed in the 1940s for the double murder of h...
1,238,en,The Godfather,1972-03-14,The Godfather,105.608,"Spanning the years 1945 to 1955, a chronicle o..."
2,240,en,The Godfather Part II,1974-12-20,The Godfather Part II,86.122,In the continuing saga of the Corleone crime f...
3,424,en,Schindler's List,1993-12-15,Schindler's List,72.147,The true story of how businessman Oskar Schind...
4,389,en,12 Angry Men,1957-04-10,12 Angry Men,47.243,The defense and the prosecution have rested an...
5,129,ja,千と千尋の神隠し,2001-07-20,Spirited Away,95.967,"A young girl, Chihiro, becomes trapped in a st..."
6,19404,hi,दिलवाले दुल्हनिया ले जायेंगे,1995-10-20,Dilwale Dulhania Le Jayenge,37.447,"Raj is a rich, carefree, happy-go-lucky second..."
7,155,en,The Dark Knight,2008-07-16,The Dark Knight,117.198,Batman raises the stakes in his war on crime. ...
8,496243,ko,기생충,2019-05-30,Parasite,94.043,"All unemployed, Ki-taek's family takes peculia..."
9,497,en,The Green Mile,1999-12-10,The Green Mile,77.179,A supernatural tale set on death row in a Sout...
10,372058,ja,君の名は。,2016-08-26,Your Name.,80.190,High schoolers Mitsuha and Taki are complete s...
11,680,en,Pulp Fiction,1994-09-10,Pulp Fiction,90.812,"A burger-loving hit man, his philosophical par..."
12,122,en,The Lord of the Rings: The Return of the King,2003-12-01,The Lord of the Rings: The Return of the King,101.646,Aragorn is revealed as the heir to the ancient...
13,13,en,Forrest Gump,1994-06-23,Forrest Gump,97.739,A man with a low IQ has accomplished great thi...
14,429,it,"Il buono, il brutto, il cattivo",1966-12-22,"The Good, the Bad and the Ugly",63.730,While the Civil War rages on between the Union...
15,769,en,GoodFellas,1990-09-12,GoodFellas,62.104,"The true story of Henry Hill, a half-Irish, ha..."
16,12477,ja,火垂るの墓,1988-04-16,Grave of the Fireflies,0.600,"In the final months of World War II, 14-year-o..."
17,637,it,La vita è bella,1997-12-20,Life Is Beautiful,40.453,A touching story of an Italian book seller of ...
18,346,ja,七人の侍,1954-04-26,Seven Samurai,42.318,A samurai answers a village's request for prot...
19,11216,it,Nuovo Cinema Paradiso,1988-11-17,Cinema Paradiso,30.838,"A filmmaker recalls his childhood, when he fel..."

In [ ]:
url1 = "https://api.themoviedb.org/3/genre/movie/list?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US"
response1 = requests.get(url1)

In [ ]:
response1

In [ ]:
response1.json()#["results"]

{'genres': [{'id': 28, 'name': 'Action'},
  {'id': 12, 'name': 'Adventure'},
  {'id': 16, 'name': 'Animation'},
  {'id': 35, 'name': 'Comedy'},
  {'id': 80, 'name': 'Crime'},
  {'id': 99, 'name': 'Documentary'},
  {'id': 18, 'name': 'Drama'},
  {'id': 10751, 'name': 'Family'},
  {'id': 14, 'name': 'Fantasy'},
  {'id': 36, 'name': 'History'},
  {'id': 27, 'name': 'Horror'},
  {'id': 10402, 'name': 'Music'},
  {'id': 9648, 'name': 'Mystery'},
  {'id': 10749, 'name': 'Romance'},
  {'id': 878, 'name': 'Science Fiction'},
  {'id': 10770, 'name': 'TV Movie'},
  {'id': 53, 'name': 'Thriller'},
  {'id': 10752, 'name': 'War'},
  {'id': 37, 'name': 'Western'}]}

In [ ]:
gen_df = pd.DataFrame(response1.json()["genres"])[["id","name"]]

In [ ]:
df1 = pd.DataFrame()

In [ ]:
url = "https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1"
response = requests.get(url)
pd.DataFrame(response.json()["results"])[["id","original_language","original_title","release_date","title","popularity","overview"]].head()

,id,original_language,original_title,release_date,title,popularity,overview
0,278,en,The Shawshank Redemption,1994-09-23,The Shawshank Redemption,119.766,Framed in the 1940s for the double murder of h...
1,238,en,The Godfather,1972-03-14,The Godfather,105.608,"Spanning the years 1945 to 1955, a chronicle o..."
2,240,en,The Godfather Part II,1974-12-20,The Godfather Part II,86.122,In the continuing saga of the Corleone crime f...
3,424,en,Schindler's List,1993-12-15,Schindler's List,72.147,The true story of how businessman Oskar Schind...
4,389,en,12 Angry Men,1957-04-10,12 Angry Men,47.243,The defense and the prosecution have rested an...

In [ ]:
for i in range(1,40):
    url = f"https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={i}"
    response = requests.get(url)
    rdf = pd.DataFrame(response.json()["results"])[["id","original_language","original_title","genre_ids","release_date","title","popularity","overview"]]
    df1 = df1.append(rdf,ignore_index = False)

<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)
<ipython-input-11-eb3a7600e683>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(rdf,ignore_index = False)

In [ ]:
df1

,id,original_language,original_title,genre_ids,release_date,title,popularity,overview
0,278,en,The Shawshank Redemption,"[18, 80]",1994-09-23,The Shawshank Redemption,119.766,Framed in the 1940s for the double murder of h...
1,238,en,The Godfather,"[18, 80]",1972-03-14,The Godfather,105.608,"Spanning the years 1945 to 1955, a chronicle o..."
2,240,en,The Godfather Part II,"[18, 80]",1974-12-20,The Godfather Part II,86.122,In the continuing saga of the Corleone crime f...
3,424,en,Schindler's List,"[18, 36, 10752]",1993-12-15,Schindler's List,72.147,The true story of how businessman Oskar Schind...
4,389,en,12 Angry Men,[18],1957-04-10,12 Angry Men,47.243,The defense and the prosecution have rested an...
...,...,...,...,...,...,...,...,...
15,83666,en,Moonrise Kingdom,"[35, 18, 10749]",2012-05-16,Moonrise Kingdom,23.073,Set on an island off the coast of New England ...
16,587272,es,Padre no hay más que uno,[35],2019-08-02,Father There Is Only One,32.463,"Javier is what we have dubbed as a ""husband-in..."
17,369299,es,¿Qué culpa tiene el niño?,"[35, 10749]",2016-05-13,Don't Blame the Kid,24.640,"After a one-night stand results in pregnancy, ..."
18,244063,nl,Jongens,"[18, 10749]",2014-01-08,Boys,18.180,Two teen track stars discover first love as th...
19,20123,sh,Dom za vešanje,"[18, 35, 80, 14]",1988-12-21,Time of the Gypsies,19.432,In this luminous tale set in the former Yugosl...

In [ ]:
gen_df.head()

   id       name
0  28     Action
1  12  Adventure
2  16  Animation
3  35     Comedy
4  80      Crime

In [ ]:
df1["genre_ids"]=df1["genre_ids"].fillna("not")

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 780 entries, 0 to 19
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 780 non-null    int64
 1   original_language  780 non-null    object
 2   original_title     780 non-null    object
 3   genre_ids          780 non-null    object
 4   release_date       780 non-null    object
 5   title              780 non-null    object
 6   popularity         780 non-null    float64
 7   overview           780 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 54.8+ KB

In [ ]:
d = {}
for i,j in zip(gen_df["id"],gen_df["name"]):
    d[i]=j

In [ ]:
d

{28: 'Action',
 12: 'Adventure',
 16: 'Animation',
 35: 'Comedy',
 80: 'Crime',
 99: 'Documentary',
 18: 'Drama',
 10751: 'Family',
 14: 'Fantasy',
 36: 'History',
 27: 'Horror',
 10402: 'Music',
 9648: 'Mystery',
 10749: 'Romance',
 878: 'Science Fiction',
 10770: 'TV Movie',
 53: 'Thriller',
 10752: 'War',
 37: 'Western'}

In [ ]:
df1["genre_ids"]

0             [18, 80]
1             [18, 80]
2             [18, 80]
3      [18, 36, 10752]
4                 [18]
            ...
15     [35, 18, 10749]
16                [35]
17         [35, 10749]
18         [18, 10749]
19    [18, 35, 80, 14]
Name: genre_ids, Length: 780, dtype: object

In [ ]:
def rep(text):

    for i in d.keys():
        if str(i) in text:
            text = text.replace(str(i),d[i])
    return text

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 780 entries, 0 to 19
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 780 non-null    int64
 1   original_language  780 non-null    object
 2   original_title     780 non-null    object
 3   genre_ids          780 non-null    object
 4   release_date       780 non-null    object
 5   title              780 non-null    object
 6   popularity         780 non-null    float64
 7   overview           780 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 54.8+ KB

In [ ]:
li = df1["genre_ids"].astype("str").str.lstrip("[").str.rstrip("]").apply(rep)#.str.split(", ")

In [ ]:
df1.insert(5,"genre",li)

In [ ]:
df1.head(34)

,id,original_language,original_title,genre_ids,release_date,genre,title,popularity,overview
0,278,en,The Shawshank Redemption,"[18, 80]",1994-09-23,"Drama, Crime",The Shawshank Redemption,119.766,Framed in the 1940s for the double murder of h...
1,238,en,The Godfather,"[18, 80]",1972-03-14,"Drama, Crime",The Godfather,105.608,"Spanning the years 1945 to 1955, a chronicle o..."
2,240,en,The Godfather Part II,"[18, 80]",1974-12-20,"Drama, Crime",The Godfather Part II,86.122,In the continuing saga of the Corleone crime f...
3,424,en,Schindler's List,"[18, 36, 10752]",1993-12-15,"Drama, History, War",Schindler's List,72.147,The true story of how businessman Oskar Schind...
4,389,en,12 Angry Men,[18],1957-04-10,Drama,12 Angry Men,47.243,The defense and the prosecution have rested an...
5,129,ja,千と千尋の神隠し,"[16, 10751, 14]",2001-07-20,"Animation, Family, Fantasy",Spirited Away,95.967,"A young girl, Chihiro, becomes trapped in a st..."
6,19404,hi,दिलवाले दुल्हनिया ले जायेंगे,"[35, 18, 10749]",1995-10-20,"Comedy, Drama, Romance",Dilwale Dulhania Le Jayenge,37.447,"Raj is a rich, carefree, happy-go-lucky second..."
7,155,en,The Dark Knight,"[18, 28, 80, 53]",2008-07-16,"Drama, Action, Crime, Thriller",The Dark Knight,117.198,Batman raises the stakes in his war on crime. ...
8,496243,ko,기생충,"[35, 53, 18]",2019-05-30,"Comedy, Thriller, Drama",Parasite,94.043,"All unemployed, Ki-taek's family takes peculia..."
9,497,en,The Green Mile,"[14, 18, 80]",1999-12-10,"Fantasy, Drama, Crime",The Green Mile,77.179,A supernatural tale set on death row in a Sout...
10,372058,ja,君の名は。,"[10749, 16, 18]",2016-08-26,"Romance, Animation, Drama",Your Name.,80.190,High schoolers Mitsuha and Taki are complete s...
11,680,en,Pulp Fiction,"[53, 80]",1994-09-10,"Thriller, Crime",Pulp Fiction,90.812,"A burger-loving hit man, his philosophical par..."
12,122,en,The Lord of the Rings: The Return of the King,"[12, 14, 28]",2003-12-01,"Adventure, Fantasy, Action",The Lord of the Rings: The Return of the King,101.646,Aragorn is revealed as the heir to the ancient...
13,13,en,Forrest Gump,"[35, 18, 10749]",1994-06-23,"Comedy, Drama, Romance",Forrest Gump,97.739,A man with a low IQ has accomplished great thi...
14,429,it,"Il buono, il brutto, il cattivo",[37],1966-12-22,Western,"The Good, the Bad and the Ugly",63.730,While the Civil War rages on between the Union...
15,769,en,GoodFellas,"[18, 80]",1990-09-12,"Drama, Crime",GoodFellas,62.104,"The true story of Henry Hill, a half-Irish, ha..."
16,12477,ja,火垂るの墓,"[16, 18, 10752]",1988-04-16,"Animation, Drama, War",Grave of the Fireflies,0.600,"In the final months of World War II, 14-year-o..."
17,637,it,La vita è bella,"[35, 18]",1997-12-20,"Comedy, Drama",Life Is Beautiful,40.453,A touching story of an Italian book seller of ...
18,346,ja,七人の侍,"[28, 18]",1954-04-26,"Action, Drama",Seven Samurai,42.318,A samurai answers a village's request for prot...
19,11216,it,Nuovo Cinema Paradiso,"[18, 10749]",1988-11-17,"Drama, Romance",Cinema Paradiso,30.838,"A filmmaker recalls his childhood, when he fel..."
0,568332,en,Taylor Swift: Reputation Stadium Tour,[10402],2018-12-31,Music,Taylor Swift: Reputation Stadium Tour,19.408,Taylor Swift takes the stage in Dallas for the...
1,550,en,Fight Club,[18],1999-10-15,Drama,Fight Club,95.218,A ticking-time-bomb insomniac and a slippery s...
2,598,pt,Cidade de Deus,"[18, 80]",2002-08-30,"Drama, Crime",City of God,43.122,"In the slums of Rio, two kids' paths diverge a..."
3,539,en,Psycho,"[27, 53, 9648]",1960-06-22,"Horror, Thriller, Mystery",Psycho,64.237,When larcenous real estate clerk Marion Crane ...
4,696374,en,Gabriel's Inferno,"[10749, 18]",2020-05-29,"Romance, Drama",Gabriel's Inferno,10.603,An intriguing and sinful exploration of seduct...
5,667257,es,Cosas imposibles,"[10751, 18]",2021-06-17,"Family, Drama",Impossible Things,12.661,"Matilde is a woman who, after the death of her..."
6,157336,en,Interstellar,"[12, 18, 878]",2014-11-05,"Adventure, Drama, Science Fiction",Interstellar,141.594,The adventures of a group of explorers who mak...
7,311,en,Once Upon a Time in America,"[18, 80]",1984-05-23,"Drama, Crime",Once Upon a Time in America,45.872,A former Prohibition-era Jewish gangster retur...
8,372754,ja,同級生,"[10749, 16]",2016-02-20,"Romance, Animation",Dou kyu sei – Classmates,13.455,"Rihito Sajo, an honor student with a perfect s..."
9,510,en,One Flew Over the Cuckoo's Nest,[18],1975-11-19,Drama,One Flew Over the Cuckoo's Nest,53.421,A petty criminal fakes insanity to serve his s...
10,724089,en,Gabriel's Inferno: Part II,"[10749, 18]",2020-07-31,"Romance, Drama",Gabriel's Inferno: Part II,8.124,Professor Gabriel Emerson finally learns the t...
11,120,en,The Lord of the Rings: The Fellowship of the Ring,"[12, 14, 28]",2001-12-18,"Adventure, Fantasy, Action",The Lord of the Rings: The Fellowship of the Ring,129.407,"Young hobbit Frodo Baggins, after inheriting a..."
12,324857,en,Spider-Man: Into the Spider-Verse,"[28, 12, 16, 878]",2018-12-06,"Action, Adventure, Animation, Science Fiction",Spider-Man: Into the Spider-Verse,95.218,Struggling to find his place in the world whil...
13,4935,ja,ハウルの動く城,"[14, 16, 12]",2004-09-09,"Fantasy, Animation, Adventure",Howl's Moving Castle,93.472,"Sophie, a young milliner, is turned into an el..."

In [ ]:
df1=df1.rename(columns = {"overview":"review"})

In [ ]:
#df1.to_csv("tmbd_movies.csv")

In [ ]:
df1 = df1.sample(200)

In [ ]:
df1["review"]=df1["review"].str.lower()
df1.review

3     a dying man in his forties recalls his childho...
10    brought back to life by an unorthodox scientis...
10    a young boy comes of age in the most peculiar ...
7     on christmas eve, three homeless people living...
17    jeffrey 'the dude' lebowski, a los angeles sla...
                            ...
9     in hong kong of 1962, mrs. chan and mr. chow, ...
4     an arrogant reporter exploits a story about a ...
0     framed in the 1940s for the double murder of h...
19    a young nurse, alma, is put in charge of elisa...
13    as garibaldi's troops begin the unification of...
Name: review, Length: 200, dtype: object

In [ ]:
import string
exclude = string.punctuation

In [ ]:
##remove punctuations

def remove_pun(text):
    return text.translate(str.maketrans("","",exclude))

df1["review"]=df1["review"].apply(remove_pun)

In [ ]:
##remove html tags

import re
def remove_html(text):
    pattern = re.compile("<.*?>")
    return pattern.sub(r"",text)

In [ ]:
df1["review"]=df1["review"].apply(remove_html)

In [ ]:
df1[df1["review"].str.contains("https?://\S+/www\.\S+",regex = True)]

Empty DataFrame
Columns: [id, original_language, original_title, genre_ids, release_date, genre, title, popularity, review]
Index: []

In [ ]:
import re
a = "i saw a man drinking <brandi> so i try to fetch details that would <<stopped>> him"
pattern = re.compile("<.*?.>")
res = pattern.sub("",a)

In [ ]:
#df1[df1["review"].str.contains("http")]

In [ ]:
s = 'Check out this website: https://example.com/www/mypage,Another link: http://example.org/www/anotherpage No URL here.'
pattern  = re.compile(r"https?://\w+\.\w+/\www/\w*")
#https?://\w+\.w+/www/\w+

In [ ]:
res = pattern.findall(s)
for i in res:
    print(i)

https://example.com/www/mypage
http://example.org/www/anotherpage

In [ ]:
##char word treatment//shorthands

short = {
    "$" : " dollar ",
    "€" : " euro ",
    "4ao" : "for adults only",
    "a.m" : "before midday",
    "a3" : "anytime anywhere anyplace",
    "aamof" : "as a matter of fact",
    "acct" : "account",
    "adih" : "another day in hell",
    "afaic" : "as far as i am concerned",
    "afaict" : "as far as i can tell",
    "afaik" : "as far as i know",
    "afair" : "as far as i remember",
    "afk" : "away from keyboard",
    "app" : "application",
    "approx" : "approximately",
    "apps" : "applications",
    "asap" : "as soon as possible",
    "asl" : "age, sex, location",
    "atk" : "at the keyboard",
    "ave." : "avenue",
    "aymm" : "are you my mother",
    "ayor" : "at your own risk",
    "b&b" : "bed and breakfast",
    "b+b" : "bed and breakfast",
    "b.c" : "before christ",
    "b2b" : "business to business",
    "b2c" : "business to customer",
    "b4" : "before",
    "b4n" : "bye for now",
    "b@u" : "back at you",
    "bae" : "before anyone else",
    "bak" : "back at keyboard",
    "bbbg" : "bye bye be good",
    "bbc" : "british broadcasting corporation",
    "bbias" : "be back in a second",
    "bbl" : "be back later",
    "bbs" : "be back soon",
    "be4" : "before",
    "bfn" : "bye for now",
    "blvd" : "boulevard",
    "bout" : "about",
    "brb" : "be right back",
    "bros" : "brothers",
    "brt" : "be right there",
    "bsaaw" : "big smile and a wink",
    "btw" : "by the way",
    "bwl" : "bursting with laughter",
    "c/o" : "care of",
    "cet" : "central european time",
    "cf" : "compare",
    "cia" : "central intelligence agency",
    "csl" : "can not stop laughing",
    "cu" : "see you",
    "cul8r" : "see you later",
    "cv" : "curriculum vitae",
    "cwot" : "complete waste of time",
    "cya" : "see you",
    "cyt" : "see you tomorrow",
    "dae" : "does anyone else",
    "dbmib" : "do not bother me i am busy",
    "diy" : "do it yourself",
    "dm" : "direct message",
    "dwh" : "during work hours",
    "e123" : "easy as one two three",
    "eet" : "eastern european time",
    "eg" : "example",
    "embm" : "early morning business meeting",
    "encl" : "enclosed",
    "encl." : "enclosed",
    "etc" : "and so on",
    "faq" : "frequently asked questions",
    "fawc" : "for anyone who cares",
    "fb" : "facebook",
    "fc" : "fingers crossed",
    "fig" : "figure",
    "fimh" : "forever in my heart",
    "ft." : "feet",
    "ft" : "featuring",
    "ftl" : "for the loss",
    "ftw" : "for the win",
    "fwiw" : "for what it is worth",
    "fyi" : "for your information",
    "g9" : "genius",
    "gahoy" : "get a hold of yourself",
    "gal" : "get a life",
    "gcse" : "general certificate of secondary education",
    "gfn" : "gone for now",
    "gg" : "good game",
    "gl" : "good luck",
    "glhf" : "good luck have fun",
    "gmt" : "greenwich mean time",
    "gmta" : "great minds think alike",
    "gn" : "good night",
    "g.o.a.t" : "greatest of all time",
    "goat" : "greatest of all time",
    "goi" : "get over it",
    "gps" : "global positioning system",
    "gr8" : "great",
    "gratz" : "congratulations",
    "gyal" : "girl",
    "h&c" : "hot and cold",
    "hp" : "horsepower",
    "hr" : "hour",
    "hrh" : "his royal highness",
    "ht" : "height",
    "ibrb" : "i will be right back",
    "ic" : "i see",
    "icq" : "i seek you",
    "icymi" : "in case you missed it",
    "idc" : "i do not care",
    "idgadf" : "i do not give a damn fuck",
    "idgaf" : "i do not give a fuck",
    "idk" : "i do not know",
    "ie" : "that is",
    "i.e" : "that is",
    "ifyp" : "i feel your pain",
    "IG" : "instagram",
    "iirc" : "if i remember correctly",
    "ilu" : "i love you",
    "ily" : "i love you",
    "imho" : "in my humble opinion",
    "imo" : "in my opinion",
    "imu" : "i miss you",
    "iow" : "in other words",
    "irl" : "in real life",
    "j4f" : "just for fun",
    "jic" : "just in case",
    "jk" : "just kidding",
    "jsyk" : "just so you know",
    "l8r" : "later",
    "lb" : "pound",
    "lbs" : "pounds",
    "ldr" : "long distance relationship",
    "lmao" : "laugh my ass off",
    "lmfao" : "laugh my fucking ass off",
    "lol" : "laughing out loud",
    "ltd" : "limited",
    "ltns" : "long time no see",
    "m8" : "mate",
    "mf" : "motherfucker",
    "mfs" : "motherfuckers",
    "mfw" : "my face when",
    "mofo" : "motherfucker",
    "mph" : "miles per hour",
    "mr" : "mister",
    "mrw" : "my reaction when",
    "ms" : "miss",
    "mte" : "my thoughts exactly",
    "nagi" : "not a good idea",
    "nbc" : "national broadcasting company",
    "nbd" : "not big deal",
    "nfs" : "not for sale",
    "ngl" : "not going to lie",
    "nhs" : "national health service",
    "nrn" : "no reply necessary",
    "nsfl" : "not safe for life",
    "nsfw" : "not safe for work",
    "nth" : "nice to have",
    "nvr" : "never",
    "nyc" : "new york city",
    "oc" : "original content",
    "og" : "original",
    "ohp" : "overhead projector",
    "oic" : "oh i see",
    "omdb" : "over my dead body",
    "omg" : "oh my god",
    "omw" : "on my way",
    "p.a" : "per annum",
    "p.m" : "after midday",
    "pm" : "prime minister",
    "poc" : "people of color",
    "pov" : "point of view",
    "pp" : "pages",
    "ppl" : "people",
    "prw" : "parents are watching",
    "ps" : "postscript",
    "pt" : "point",
    "ptb" : "please text back",
    "pto" : "please turn over",
    "qpsa" : "what happens", #"que pasa",
    "ratchet" : "rude",
    "rbtl" : "read between the lines",
    "rlrt" : "real life retweet",
    "rofl" : "rolling on the floor laughing",
    "roflol" : "rolling on the floor laughing out loud",
    "rotflmao" : "rolling on the floor laughing my ass off",
    "rt" : "retweet",
    "ruok" : "are you ok",
    "sfw" : "safe for work",
    "sk8" : "skate",
    "smh" : "shake my head",
    "sq" : "square",
    "srsly" : "seriously",
    "ssdd" : "same stuff different day",
    "tbh" : "to be honest",
    "tbs" : "tablespooful",
    "tbsp" : "tablespooful",
    "tfw" : "that feeling when",
    "thks" : "thank you",
    "tho" : "though",
    "thx" : "thank you",
    "tia" : "thanks in advance",
    "til" : "today i learned",
    "tl;dr" : "too long i did not read",
    "tldr" : "too long i did not read",
    "tmb" : "tweet me back",
    "tntl" : "trying not to laugh",
    "ttyl" : "talk to you later",
    "u" : "you",
    "u2" : "you too",
    "u4e" : "yours for ever",
    "utc" : "coordinated universal time",
    "w/" : "with",
    "w/o" : "without",
    "w8" : "wait",
    "wassup" : "what is up",
    "wb" : "welcome back",
    "wtf" : "what the fuck",
    "wtg" : "way to go",
    "wtpa" : "where the party at",
    "wuf" : "where are you from",
    "wuzup" : "what is up",
    "wywh" : "wish you were here",
    "yd" : "yard",
    "ygtr" : "you got that right",
    "ynk" : "you never know",
    "zzz" : "sleeping bored and tired"
}

In [ ]:
short

{'$': ' dollar ',
 '€': ' euro ',
 '4ao': 'for adults only',
 'a.m': 'before midday',
 'a3': 'anytime anywhere anyplace',
 'aamof': 'as a matter of fact',
 'acct': 'account',
 'adih': 'another day in hell',
 'afaic': 'as far as i am concerned',
 'afaict': 'as far as i can tell',
 'afaik': 'as far as i know',
 'afair': 'as far as i remember',
 'afk': 'away from keyboard',
 'app': 'application',
 'approx': 'approximately',
 'apps': 'applications',
 'asap': 'as soon as possible',
 'asl': 'age, sex, location',
 'atk': 'at the keyboard',
 'ave.': 'avenue',
 'aymm': 'are you my mother',
 'ayor': 'at your own risk',
 'b&b': 'bed and breakfast',
 'b+b': 'bed and breakfast',
 'b.c': 'before christ',
 'b2b': 'business to business',
 'b2c': 'business to customer',
 'b4': 'before',
 'b4n': 'bye for now',
 'b@u': 'back at you',
 'bae': 'before anyone else',
 'bak': 'back at keyboard',
 'bbbg': 'bye bye be good',
 'bbc': 'british broadcasting corporation',
 'bbias': 'be back in a second',
 'bbl': 'be back later',
 'bbs': 'be back soon',
 'be4': 'before',
 'bfn': 'bye for now',
 'blvd': 'boulevard',
 'bout': 'about',
 'brb': 'be right back',
 'bros': 'brothers',
 'brt': 'be right there',
 'bsaaw': 'big smile and a wink',
 'btw': 'by the way',
 'bwl': 'bursting with laughter',
 'c/o': 'care of',
 'cet': 'central european time',
 'cf': 'compare',
 'cia': 'central intelligence agency',
 'csl': 'can not stop laughing',
 'cu': 'see you',
 'cul8r': 'see you later',
 'cv': 'curriculum vitae',
 'cwot': 'complete waste of time',
 'cya': 'see you',
 'cyt': 'see you tomorrow',
 'dae': 'does anyone else',
 'dbmib': 'do not bother me i am busy',
 'diy': 'do it yourself',
 'dm': 'direct message',
 'dwh': 'during work hours',
 'e123': 'easy as one two three',
 'eet': 'eastern european time',
 'eg': 'example',
 'embm': 'early morning business meeting',
 'encl': 'enclosed',
 'encl.': 'enclosed',
 'etc': 'and so on',
 'faq': 'frequently asked questions',
 'fawc': 'for anyone who cares',
 'fb': 'facebook',
 'fc': 'fingers crossed',
 'fig': 'figure',
 'fimh': 'forever in my heart',
 'ft.': 'feet',
 'ft': 'featuring',
 'ftl': 'for the loss',
 'ftw': 'for the win',
 'fwiw': 'for what it is worth',
 'fyi': 'for your information',
 'g9': 'genius',
 'gahoy': 'get a hold of yourself',
 'gal': 'get a life',
 'gcse': 'general certificate of secondary education',
 'gfn': 'gone for now',
 'gg': 'good game',
 'gl': 'good luck',
 'glhf': 'good luck have fun',
 'gmt': 'greenwich mean time',
 'gmta': 'great minds think alike',
 'gn': 'good night',
 'g.o.a.t': 'greatest of all time',
 'goat': 'greatest of all time',
 'goi': 'get over it',
 'gps': 'global positioning system',
 'gr8': 'great',
 'gratz': 'congratulations',
 'gyal': 'girl',
 'h&c': 'hot and cold',
 'hp': 'horsepower',
 'hr': 'hour',
 'hrh': 'his royal highness',
 'ht': 'height',
 'ibrb': 'i will be right back',
 'ic': 'i see',
 'icq': 'i seek you',
 'icymi': 'in case you missed it',
 'idc': 'i do not care',
 'idgadf': 'i do not give a damn fuck',
 'idgaf': 'i do not give a fuck',
 'idk': 'i do not know',
 'ie': 'that is',
 'i.e': 'that is',
 'ifyp': 'i feel your pain',
 'IG': 'instagram',
 'iirc': 'if i remember correctly',
 'ilu': 'i love you',
 'ily': 'i love you',
 'imho': 'in my humble opinion',
 'imo': 'in my opinion',
 'imu': 'i miss you',
 'iow': 'in other words',
 'irl': 'in real life',
 'j4f': 'just for fun',
 'jic': 'just in case',
 'jk': 'just kidding',
 'jsyk': 'just so you know',
 'l8r': 'later',
 'lb': 'pound',
 'lbs': 'pounds',
 'ldr': 'long distance relationship',
 'lmao': 'laugh my ass off',
 'lmfao': 'laugh my fucking ass off',
 'lol': 'laughing out loud',
 'ltd': 'limited',
 'ltns': 'long time no see',
 'm8': 'mate',
 'mf': 'motherfucker',
 'mfs': 'motherfuckers',
 'mfw': 'my face when',
 'mofo': 'motherfucker',
 'mph': 'miles per hour',
 'mr': 'mister',
 'mrw': 'my reaction when',
 'ms': 'miss',
 'mte': 'my thoughts exactly',
 'nagi': 'not a good idea',
 'nbc': 'national broadcasting company',
 'nbd': 'not big deal',
 'nfs': 'not for sale',
 'ngl': 'not going to lie',
 'nhs': 'national health service',
 'nrn': 'no reply necessary',
 'nsfl': 'not safe for life',
 'nsfw': 'not safe for work',
 'nth': 'nice to have',
 'nvr': 'never',
 'nyc': 'new york city',
 'oc': 'original content',
 'og': 'original',
 'ohp': 'overhead projector',
 'oic': 'oh i see',
 'omdb': 'over my dead body',
 'omg': 'oh my god',
 'omw': 'on my way',
 'p.a': 'per annum',
 'p.m': 'after midday',
 'pm': 'prime minister',
 'poc': 'people of color',
 'pov': 'point of view',
 'pp': 'pages',
 'ppl': 'people',
 'prw': 'parents are watching',
 'ps': 'postscript',
 'pt': 'point',
 'ptb': 'please text back',
 'pto': 'please turn over',
 'qpsa': 'what happens',
 'ratchet': 'rude',
 'rbtl': 'read between the lines',
 'rlrt': 'real life retweet',
 'rofl': 'rolling on the floor laughing',
 'roflol': 'rolling on the floor laughing out loud',
 'rotflmao': 'rolling on the floor laughing my ass off',
 'rt': 'retweet',
 'ruok': 'are you ok',
 'sfw': 'safe for work',
 'sk8': 'skate',
 'smh': 'shake my head',
 'sq': 'square',
 'srsly': 'seriously',
 'ssdd': 'same stuff different day',
 'tbh': 'to be honest',
 'tbs': 'tablespooful',
 'tbsp': 'tablespooful',
 'tfw': 'that feeling when',
 'thks': 'thank you',
 'tho': 'though',
 'thx': 'thank you',
 'tia': 'thanks in advance',
 'til': 'today i learned',
 'tl;dr': 'too long i did not read',
 'tldr': 'too long i did not read',
 'tmb': 'tweet me back',
 'tntl': 'trying not to laugh',
 'ttyl': 'talk to you later',
 'u': 'you',
 'u2': 'you too',
 'u4e': 'yours for ever',
 'utc': 'coordinated universal time',
 'w/': 'with',
 'w/o': 'without',
 'w8': 'wait',
 'wassup': 'what is up',
 'wb': 'welcome back',
 'wtf': 'what the fuck',
 'wtg': 'way to go',
 'wtpa': 'where the party at',
 'wuf': 'where are you from',
 'wuzup': 'what is up',
 'wywh': 'wish you were here',
 'yd': 'yard',
 'ygtr': 'you got that right',
 'ynk': 'you never know',
 'zzz': 'sleeping bored and tired'}

In [ ]:
def sh_conversion(text):
    new_text = []
    for w in text.split():
        if w in short:
            new_text.append(short[w])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [ ]:
df1["review"].apply(sh_conversion)

3     a dying man in his forties recalls his childho...
10    brought back to life by an unorthodox scientis...
10    a young boy comes of age in the most peculiar ...
7     on christmas eve three homeless people living ...
17    jeffrey the dude lebowski a los angeles slacke...
                            ...
9     in hong kong of 1962 mrs chan and mister chow ...
4     an arrogant reporter exploits a story about a ...
0     framed in the 1940s for the double murder of h...
19    a young nurse alma is put in charge of elisabe...
13    as garibaldis troops begin the unification of ...
Name: review, Length: 200, dtype: object

In [ ]:
##spell correction
#!pip install textblob

from textblob import TextBlob

In [ ]:
def spell(text):
    t = TextBlob(text)
    return t.correct().string

In [ ]:
df1["review"].apply(spell)

3     a dying man in his forties recalls his childho...
10    brought back to life by an orthodox scientist ...
10    a young boy comes of age in the most peculiar ...
7     on christmas eve three homeless people living ...
17    geoffrey the due lebowski a los angeles slacke...
                            ...
9     in long long of 1962 mrs than and mr how a jou...
4     an arrogant reporter exploits a story about a ...
0     framed in the 1940s for the double murder of h...
19    a young nurse alma is put in charge of elisabe...
13    as garibaldis troops begin the purification of...
Name: review, Length: 200, dtype: object

In [ ]:
#remove stopwords

from nltk.corpus import stopwords
import spacy
nlp = spacy.load("en_core_web_sm")

In [ ]:
def remove_stop(text):
    l1 = []
    doc = nlp(text)
    for i in doc:
        if not i.is_stop:
            l1.append(i.text)
    return " ".join(l1)

In [ ]:
df1["review"]=df1["review"].apply(remove_stop)

In [ ]:
df1["review"]

3     dying man forties recalls childhood mother war...
10    brought life unorthodox scientist young woman ...
10    young boy comes age peculiar circumstances ton...
7     christmas eve homeless people living streets t...
17    jeffrey dude lebowski los angeles slacker want...
                            ...
9     hong kong 1962 mrs chan mr chow journalist nei...
4     arrogant reporter exploits story man trapped c...
0     framed 1940s double murder wife lover upstandi...
19    young nurse alma charge elisabeth vogler actre...
13    garibaldis troops begin unification italy 1860...
Name: review, Length: 200, dtype: object

In [ ]:
import nltk
nltk.download('punkt')
##tokenize
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [ ]:
df1["review"]=df1["review"].apply(lambda x: word_tokenize(x))

In [ ]:
##lemmetization
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
wl = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to /root/nltk_data...

In [ ]:
def lemmatize_text(text):
    lemmatized_words = [wl.lemmatize(word) for word in text]
    return ' '.join(lemmatized_words)

In [ ]:
df1["review"]=df1["review"].apply(lemmatize_text)

In [ ]:
## text representation==>countvectorizer--Bagofwords
import sklearn
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer()
bow = cv.fit_transform(df1["review"])

In [ ]:
bow[1].toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [ ]:
bow[1].toarray().shape

(1, 2812)

In [ ]:
cv.vocabulary_

{'dying': 749,
 'man': 1546,
 'forty': 1004,
 'recall': 2032,
 'childhood': 416,
 'mother': 1665,
 'war': 2718,
 'personal': 1855,
 'moment': 1654,
 'tell': 2497,
 'juxtapose': 1391,
 'pivotal': 1879,
 'soviet': 2348,
 'history': 1204,
 'daily': 580,
 'life': 1473,
 'brought': 326,
 'unorthodox': 2643,
 'scientist': 2202,
 'young': 2800,
 'woman': 2772,
 'run': 2162,
 'debauched': 604,
 'lawyer': 1438,
 'whirlwind': 2743,
 'adventure': 74,
 'continent': 512,
 'free': 1020,
 'prejudice': 1924,
 'time': 2529,
 'grows': 1130,
 'steadfast': 2389,
 'purpose': 1975,
 'stand': 2380,
 'equality': 823,
 'liberation': 1471,
 'boy': 306,
 'come': 466,
 'age': 84,
 'peculiar': 1842,
 'circumstance': 430,
 'tonight': 2543,
 'papa': 1814,
 'grandpa': 1112,
 'taking': 2476,
 'work': 2775,
 'old': 1769,
 'wooden': 2774,
 'boat': 283,
 'row': 2158,
 'far': 916,
 'sea': 2207,
 'land': 1430,
 'sight': 2285,
 'stop': 2401,
 'wait': 2707,
 'big': 258,
 'surprise': 2451,
 'awaits': 199,
 'discovers': 687,
 'family': 910,
 'unusual': 2652,
 'line': 1481,
 'follow': 982,
 'example': 856,
 'able': 38,
 'find': 961,
 'way': 2728,
 'midst': 1620,
 'conflicting': 496,
 'opinion': 1781,
 'timeworn': 2530,
 'tradition': 2558,
 'christmas': 426,
 'eve': 842,
 'homeless': 1215,
 'people': 1845,
 'living': 1489,
 'street': 2408,
 'tokyo': 2538,
 'discover': 685,
 'newborn': 1723,
 'baby': 204,
 'trash': 2572,
 'set': 2244,
 'parent': 1817,
 'jeffrey': 1355,
 'dude': 744,
 'lebowski': 1452,
 'los': 1506,
 'angeles': 132,
 'slacker': 2309,
 'want': 2716,
 'bowl': 302,
 'drink': 737,
 'white': 2745,
 'russian': 2166,
 'mistaken': 1647,
 'wheelchairbound': 2742,
 'millionaire': 1631,
 'dragged': 726,
 'strange': 2405,
 'series': 2241,
 'event': 845,
 'involving': 1329,
 'nihilist': 1733,
 'adult': 73,
 'film': 956,
 'producer': 1946,
 'ferret': 943,
 'errant': 829,
 'toe': 2535,
 'large': 1432,
 'sum': 2436,
 'money': 1655,
 'following': 984,
 'death': 601,
 'district': 703,
 'attorney': 187,
 'harvey': 1162,
 'dent': 639,
 'batman': 229,
 'assumes': 178,
 'responsibility': 2093,
 'crime': 554,
 'protect': 1964,
 'late': 1434,
 'reputation': 2079,
 'subsequently': 2426,
 'hunted': 1242,
 'gotham': 1102,
 'city': 433,
 'police': 1895,
 'department': 641,
 'year': 2797,
 'later': 1436,
 'encounter': 800,
 'mysterious': 1685,
 'selina': 2228,
 'kyle': 1420,
 'villainous': 2688,
 'bane': 218,
 'new': 1722,
 'terrorist': 2504,
 'leader': 1441,
 'overwhelms': 1806,
 'gothams': 1103,
 'finest': 963,
 'dark': 589,
 'knight': 1409,
 'resurfaces': 2100,
 'branded': 308,
 'enemy': 803,
 'beginning': 241,
 '1940s': 12,
 'france': 1012,
 'occupied': 1756,
 'nazi': 1703,
 'force': 991,
 'lived': 1487,
 'jewish': 1360,
 'joffo': 1366,
 'happy': 1154,
 'tightknit': 2527,
 'see': 2218,
 'future': 1039,
 'darken': 590,
 'member': 1595,
 'forced': 992,
 'wear': 2731,
 'yellow': 2798,
 'star': 2383,
 'fearing': 934,
 'worst': 2785,
 'organized': 1795,
 'flee': 976,
 'zone': 2809,
 'south': 2345,
 'country': 534,
 'maurice': 1581,
 'joseph': 1376,
 'leave': 1450,
 'order': 1789,
 'maximize': 1582,
 'chance': 396,
 'finding': 962,
 'older': 1770,
 'brother': 325,
 'settled': 2245,
 'nice': 1729,
 'left': 1455,
 'device': 665,
 'demonstrate': 637,
 'incredible': 1280,
 'cleverness': 445,
 'courage': 536,
 'ingenuity': 1294,
 'escape': 832,
 'invasion': 1325,
 'try': 2591,
 'reunite': 2106,
 'frank': 1015,
 'single': 2297,
 'raising': 2005,
 'child': 414,
 'prodigy': 1945,
 'niece': 1731,
 'mary': 1568,
 'drawn': 731,
 'custody': 575,
 'battle': 230,
 'jack': 1343,
 'torrance': 2549,
 'accepts': 45,
 'caretaker': 364,
 'job': 1364,
 'overlook': 1805,
 'hotel': 1229,
 'wife': 2750,
 'wendy': 2738,
 'son': 2336,
 'danny': 586,
 'live': 1486,
 'isolated': 1335,
 'rest': 2094,
 'world': 2779,
 'winter': 2760,
 'nt': 1749,
 'prepared': 1926,
 'madness': 1532,
 'lurks': 1526,
 'working': 2777,
 'underground': 2617,
 'fix': 970,
 'water': 2727,
 'main': 1538,
 'brooklyn': 324,
 'plumber': 1893,
 'mario': 1559,
 'luigi': 1522,
 'transported': 2569,
 'pipe': 1876,
 'wander': 2714,
 'magical': 1534,
 'separated': 2239,
 'embarks': 787,
 'epic': 821,
 'quest': 1987,
 'noriko': 1738,
 'perfectly': 1847,
 'home': 1214,
 'widowed': 2749,
 'father': 928,
 'shukichi': 2277,
 'plan': 1883,
 'marry': 1565,
 'aunt': 193,
 'masa': 1569,
 'convinces': 522,
 'marries': 1564,
 '27yearold': 32,
 'daughter': 592,
 'soon': 2339,
 'likely': 1478,
 'remain': 2064,
 'resists': 2087,
 'matchmaking': 1574,
 'deceive': 607,
 'sacrifice': 2170,
 'happiness': 1153,
 'belief': 244,
 'right': 2125,
 'near': 1705,
 'weary': 2732,
 'logan': 1495,
 'care': 361,
 'ailing': 94,
 'professor': 1949,
 'hideout': 1192,
 'mexican': 1610,
 'border': 294,
 'attempt': 183,
 'hide': 1191,
 'legacy': 1457,
 'upended': 2656,
 'mutant': 1683,
 'arrives': 163,
 'pursued': 1977,
 'tramp': 2565,
 'abandoned': 35,
 'change': 397,
 'heart': 1171,
 'ache': 55,
 'reunited': 2107,
 'inspiring': 1313,
 'true': 2587,
 'story': 2403,
 'richard': 2122,
 'montañez': 1656,
 'frito': 1030,
 'lay': 1439,
 'janitor': 1350,
 'channeled': 399,
 'american': 122,
 'heritage': 1185,
 'upbringing': 2655,
 'turn': 2595,
 'iconic': 1249,
 'flamin': 972,
 'hot': 1228,
 'cheetos': 409,
 'snack': 2319,
 'disrupted': 699,
 'food': 987,
 'industry': 1287,
 'global': 1085,
 'pop': 1902,
 'culture': 569,
 'phenomenon': 1861,
 'avenger': 195,
 'ally': 112,
 'continued': 513,
 'threat': 2524,
 'hero': 1187,
 'handle': 1146,
 'danger': 583,
 'emerged': 790,
 'cosmic': 530,
 'shadow': 2252,
 'thanos': 2510,
 'despot': 653,
 'intergalactic': 1320,
 'infamy': 1289,
 'goal': 1088,
 'collect': 460,
 'infinity': 1291,
 'stone': 2400,
 'artifact': 169,
 'unimaginable': 2630,
 'power': 1916,
 'use': 2662,
 'inflict': 1292,
 'twisted': 2601,
 'reality': 2023,
 'fought': 1007,
 'led': 1453,
 'fate': 926,
 'earth': 754,
 'existence': 869,
 'uncertain': 2612,
 'raised': 2004,
 'povertystricken': 1914,
 'slum': 2314,
 '16yearold': 5,
 'girl': 1081,
 'named': 1693,
 'starr': 2385,
 'attends': 184,
 'suburban': 2427,
 'prep': 1925,
 'school': 2199,
 'witness': 2767,
 'officer': 1765,
 'shoot': 2269,
 'unarmed': 2609,
 'best': 252,
 'friend': 1024,
 'torn': 2548,
 'different': 672,
 'speak': 2353,
 'truth': 2590,
 'agnès': 87,
 'varda': 2670,
 'eloquently': 783,
 'capture': 359,
 'paris': 1818,
 'sixty': 2305,
 'realtime': 2028,
 'portrait': 1905,
 'singer': 2295,
 'adrift': 72,
 'test': 2505,
 'result': 2098,
 'biopsy': 266,
 'chronicle': 427,
 'minute': 1637,
 'cléo': 455,
 'spirited': 2366,
 'mix': 1651,
 'vivid': 2699,
 'vérité': 2706,
 'melodrama': 1594,
 'featuring': 935,
 'score': 2204,
 'michel': 1613,
 'legrand': 1461,
 'cameo': 351,
 'jeanluc': 1353,
 'godard': 1092,
 'anna': 135,
 'karina': 1393,
 'gifted': 1076,
 'hand': 1144,
 'ben': 246,
 'carson': 366,
 'movie': 1673,
 'based': 227,
 'worldrenowned': 2781,
 'neurosurgeon': 1720,
 '1961': 16,
 '1987': 24,
 'raj': 2006,
 'rich': 2121,
 'carefree': 363,
 'happygolucky': 1155,
 'second': 2212,
 'generation': 1055,
 'nri': 1748,
 'simran': 2293,
 'chaudhary': 406,
 'baldev': 210,
 'singh': 2296,
 'spite': 2367,
 'strict': 2411,
 'adherence': 64,
 'indian': 1283,
 'value': 2668,
 'india': 1282,
 'married': 1563,
 'fiancé': 947,
 'leaf': 1444,
 'mission': 1645,
 'claim': 436,
 'lady': 1423,
 'love': 1511,
 'nose': 1744,
 'begin': 240,
 'saga': 2174,
 'dog': 714,
 'nearhuman': 1707,
 'soul': 2342,
 'philosopher': 1863,
 'mind': 1633,
 'evaluates': 841,
 'lesson': 1466,
 'learned': 1447,
 'human': 1238,
 'owner': 1808,
 'racecar': 1995,
 'driver': 739,
 'luminous': 1524,
 'tale': 2477,
 'yugoslavia': 2804,
 'perhan': 1850,
 'engaging': 807,
 'romany': 2150,
 'telekinetic': 2495,
 'seduced': 2216,
 'quickcash': 1988,
 'petty': 1860,
 'threatens': 2526,
 'destroy': 656,
 'group': 1128,
 'idealistic': 1251,
 'men': 1597,
 'join': 1371,
 'german': 1067,
 'army': 160,
 'assigned': 175,
 'western': 2741,
 'patriotism': 1836,
 'destroyed': 657,
 'harsh': 1160,
 'combat': 465,
 'mentally': 1600,
 'ill': 1261,
 'wrongfully': 2792,
 'imprisoned': 1273,
 'murder': 1676,
 'relationship': 2057,
 'forest': 995,
 'pacific': 1809,
 'northwest': 1743,
 'kid': 1397,
 'assimilate': 176,
 'society': 2325,
 'civil': 434,
 'rage': 2000,
 'union': 2631,
 'confederacy': 492,
 'quiet': 1990,
 'loner': 1498,
 'ruthless': 2168,
 'hitman': 1208,
 'bandit': 217,
 'comb': 464,
 'southwest': 2347,
 'search': 2210,
 'strongbox': 2415,
 'containing': 508,
 '200000': 25,
 'stolen': 2399,
 'gold': 1096,
 'germany': 1068,
 '1944': 13,
 'leyna': 1469,
 '15year': 3,
 'black': 269,
 'african': 80,
 'meet': 1591,
 'lutz': 1527,
 'compassionate': 477,
 'hitler': 1207,
 'youth': 2803,
 'prominent': 1956,
 'soldier': 2328,
 'form': 999,
 'unlikely': 2638,
 'connection': 499,
 'quickly': 1989,
 'changing': 398,
 'matko': 1580,
 'small': 2315,
 'hustler': 1246,
 'danube': 587,
 '17yearold': 7,
 'zare': 2807,
 'failed': 900,
 'business': 340,
 'deal': 600,
 'owes': 1807,
 'successful': 2430,
 'gangster': 1048,
 'dadan': 579,
 'sister': 2301,
 'afrodita': 82,
 'desperately': 651,
 'strike': 2412,
 'criminal': 555,
 'luke': 1523,
 'jackson': 1344,
 'sentenced': 2237,
 'florida': 980,
 'prison': 1938,
 'farm': 917,
 'play': 1887,
 'rule': 2160,
 'sadistic': 2171,
 'warden': 2720,
 'yard': 2796,
 'resident': 2086,
 'heavy': 1174,
 'dragline': 727,
 'end': 801,
 'admiring': 67,
 'guy': 1138,
 'unbreakable': 2611,
 'bravado': 309,
 'face': 894,
 'repeated': 2075,
 'stint': 2395,
 'dreaded': 732,
 'solitary': 2330,
 'confinement': 493,
 'cell': 385,
 'box': 303,
 'rebel': 2030,
 'fellow': 940,
 'convict': 520,
 'thorn': 2520,
 'elite': 781,
 'oldfashioned': 1771,
 'boarding': 282,
 'england': 808,
 'passionate': 1831,
 'english': 809,
 'teacher': 2488,
 'inspires': 1312,
 'student': 2419,
 'convention': 519,
 'seize': 2224,
 'potential': 1911,
 'day': 594,
 'courting': 538,
 'disdain': 690,
 'stern': 2392,
 'headmaster': 1168,
 'exasperated': 857,
 'number': 1751,
 'camp': 352,
 'relatively': 2059,
 'allied': 110,
 'prisoner': 1939,
 'relocate': 2063,
 'highsecurity': 1195,
 'escapeproof': 834,
 'sit': 2302,
 'remainder': 2065,
 'undaunted': 2616,
 'ambitious': 120,
 'ii': 1259,
 'nemo': 1715,
 'adventurous': 75,
 'clownfish': 452,
 'unexpectedly': 2625,
 'taken': 2474,
 'great': 1116,
 'barrier': 226,
 'reef': 2045,
 'dentist': 640,
 'office': 1764,
 'aquarium': 152,
 'worrisome': 2783,
 'marlin': 1561,
 'friendly': 1025,
 'forgetful': 998,
 'fish': 968,
 'dory': 721,
 'bring': 318,
 'meeting': 1592,
 'vegetarian': 2674,
 'shark': 2258,
 'surfer': 2450,
 'turtle': 2597,
 'hypnotic': 1248,
 'jellyfish': 1356,
 'hungry': 1241,
 'seagull': 2208,
 '1980s': 22,
 'standup': 2382,
 'comedian': 467,
 'driven': 738,
 'insane': 1305,
 'chaos': 400,
 'infamous': 1288,
 'psychopathic': 1970,
 'figure': 954,
 '1970s': 21,
 'london': 1496,
 'amidst': 124,
 'punk': 1973,
 'rock': 2140,
 'revolution': 2114,
 'grifter': 1124,
 'estella': 838,
 'determined': 662,
 'design': 648,
 'befriends': 238,
 'pair': 1811,
 'thief': 2513,
 'appreciate': 149,
 'appetite': 147,
 'mischief': 1640,
 'build': 332,
 'flair': 971,
 'fashion': 921,
 'catch': 376,
 'eye': 892,
 'baroness': 225,
 'von': 2703,
 'hellman': 1181,
 'legend': 1458,
 'devastatingly': 663,
 'chic': 412,
 'terrifyingly': 2502,
 'haute': 1164,
 'motion': 1667,
 'course': 537,
 'revelation': 2109,
 'cause': 380,
 'embrace': 789,
 'wicked': 2746,
 'raucous': 2016,
 'fashionable': 922,
 'revengebent': 2111,
 'cruella': 560,
 '2014': 26,
 'restorative': 2096,
 'justice': 1389,
 'programme': 1953,
 'offered': 1763,
 'safe': 2173,
 'space': 2349,
 'supervised': 2445,
 'dialogue': 669,
 'offender': 1761,
 'victim': 2681,
 'grégoire': 1133,
 'nawelle': 1702,
 'sabine': 2169,
 'heist': 1179,
 'violent': 2691,
 'robbery': 2138,
 'agree': 89,
 'discussion': 689,
 'alongside': 114,
 'nassim': 1696,
 'issa': 1336,
 'thomas': 2519,
 'convicted': 521,
 'chloé': 418,
 'sexual': 2250,
 'abuse': 42,
 'prepares': 1927,
 'agressor': 90,
 'learning': 1448,
 'moved': 1672,
 'town': 2554,
 'seven': 2246,
 'month': 1657,
 'passed': 1829,
 'culprit': 567,
 'case': 367,
 'mildred': 1627,
 'hayes': 1166,
 'make': 1542,
 'bold': 287,
 'painting': 1810,
 'sign': 2286,
 'leading': 1443,
 'controversial': 518,
 'message': 1605,
 'directed': 678,
 'bill': 261,
 'willoughby': 2754,
 'revered': 2112,
 'chief': 413,
 'secondincommand': 2213,
 'jason': 1352,
 'dixon': 709,
 'immature': 1266,
 'penchant': 1844,
 'violence': 2690,
 'get': 1070,
 'involved': 1328,
 'ebbing': 761,
 'law': 1437,
 'enforcement': 805,
 'exacerbated': 854,
 'raf': 1998,
 'pilot': 1873,
 'miraculously': 1639,
 'survives': 2458,
 'bailing': 208,
 'aeroplane': 77,
 'parachute': 1816,
 'fall': 905,
 'radio': 1997,
 'operator': 1780,
 'official': 1766,
 'realise': 2021,
 'mistake': 1646,
 'dispatch': 698,
 'angel': 131,
 'elderly': 776,
 'shukishi': 2278,
 'tomi': 2542,
 'long': 1499,
 'journey': 1378,
 'seaside': 2211,
 'village': 2687,
 'visit': 2696,
 'elder': 775,
 'koichi': 1413,
 'doctor': 711,
 'shige': 2265,
 'hairdresser': 1141,
 'spend': 2358,
 'aged': 85,
 'widow': 2748,
 'younger': 2801,
 'killed': 1400,
 'inlaws': 1300,
 'company': 476,
 'prohibitionera': 1954,
 'return': 2105,
 'lower': 1516,
 'east': 757,
 'manhattan': 1548,
 'thirty': 2518,
 'confront': 497,
 'ghost': 1072,
 'regret': 2054,
 'pus': 1980,
 'boot': 293,
 'passion': 1830,
 'toll': 2540,
 'burned': 338,
 'leaving': 1451,
 'mythical': 1688,
 'wish': 2766,
 'restore': 2097,
 'found': 1008,
 'inside': 1309,
 'shining': 2266,
 'stalk': 2377,
 'bamboo': 214,
 'cutter': 576,
 'tiny': 2531,
 'rapidly': 2013,
 'exquisite': 886,
 'princess': 1937,
 'enthrals': 817,
 'ultimately': 2607,
 'obsessive': 1755,
 'master': 1570,
 'neil': 1713,
 'mccauley': 1584,
 'lead': 1440,
 'topnotch': 2546,
 'crew': 553,
 'daring': 588,
 'detective': 661,
 'vincent': 2689,
 'hanna': 1149,
 'pursues': 1978,
 'recognizes': 2037,
 'respect': 2090,
 'ability': 37,
 'dedication': 615,
 'aware': 201,
 'catandmouse': 373,
 'game': 1045,
 'inherits': 1298,
 'castle': 371,
 'grandfather': 1110,
 'famous': 912,
 'dr': 725,
 'victor': 2682,
 'frankenstein': 1016,
 'funny': 1038,
 'hunchback': 1240,
 'pretty': 1930,
 'lab': 1422,
 'assistant': 177,
 'housekeeper': 1233,
 'delusional': 633,
 'book': 292,
 'mad': 1531,
 'described': 645,
 'reanimation': 2029,
 'experiment': 877,
 'suddenly': 2431,
 'red': 2043,
 'ribbon': 2118,
 'evil': 852,
 'organization': 1794,
 'goku': 1095,
 'past': 1832,
 'reformed': 2048,
 'created': 547,
 'mightier': 1622,
 'android': 129,
 'gamma': 1046,
 'seek': 2219,
 'vengeance': 2675,
 'bounty': 299,
 'hunter': 1243,
 'pursuit': 1979,
 'el': 774,
 'indio': 1286,
 'wanted': 2717,
 'fugitive': 1034,
 'territory': 2503,
 'gang': 1047,
 'botched': 298,
 'indicates': 1285,
 'informant': 1293,
 'pressure': 1929,
 'mount': 1669,
 'aftermath': 83,
 'warehouse': 2721,
 'begets': 239,
 'survivor': 2459,
 'veteran': 2680,
 'mr': 1674,
 'newcomer': 1724,
 'orange': 1787,
 'parolee': 1821,
 'blonde': 276,
 'bickering': 255,
 'weasel': 2733,
 'pink': 1875,
 'eddie': 765,
 'unravel': 2646,
 'assassin': 173,
 'shot': 2273,
 'employer': 798,
 'assassination': 174,
 'circle': 429,
 'plot': 1892,
 'kill': 1399,
 'bloody': 277,
 'affair': 78,
 'complete': 482,
 'edit': 766,
 'twopart': 2602,
 'martial': 1567,
 'art': 166,
 'action': 57,
 'vol': 2701,
 'originally': 1796,
 'scheduled': 2196,
 'released': 2060,
 'hour': 1230,
 'running': 2164,
 'split': 2368,
 'part': 1823,
 'spark': 2352,
 'creature': 551,
 'fiercely': 951,
 'independent': 1281,
 'stray': 2407,
 'kitten': 1408,
 'pit': 1878,
 'bull': 334,
 'experience': 875,
 'friendship': 1026,
 'carrying': 365,
 'flawlessly': 975,
 'planned': 1885,
 'hit': 1205,
 'jef': 1354,
 'costello': 532,
 'contract': 515,
 'killer': 1401,
 'samurai': 2183,
 'instinct': 1316,
 'caught': 379,
 'persistent': 1853,
 'investigator': 1327,
 'armor': 159,
 'fedora': 936,
 'trench': 2577,
 'coat': 458,
 'francis': 1013,
 'memory': 1596,
 'horrible': 1223,
 'fiancée': 948,
 'jane': 1349,
 'recently': 2036,
 'went': 2739,
 'alan': 100,
 'cabinet': 344,
 'caligari': 347,
 'exhibit': 866,
 'show': 2275,
 'somnambulist': 2335,
 'cesare': 389,
 'awakens': 200,
 'deathlike': 602,
 'sleep': 2311,
 'paul': 1837,
 'atreides': 179,
 'brilliant': 317,
 'born': 296,
 'destiny': 655,
 'understanding': 2619,
 'travel': 2573,
 'dangerous': 584,
 'planet': 1884,
 'universe': 2634,
 'ensure': 814,
 'malevolent': 1544,
 'explode': 878,
 'conflict': 494,
 'exclusive': 862,
 'supply': 2447,
 'precious': 1920,
 'resource': 2089,
 'existencea': 870,
 'commodity': 473,
 'capable': 356,
 'unlocking': 2640,
 'humanity': 1239,
 'greatest': 1118,
 'potentialonly': 1912,
 'conquer': 501,
 'fear': 932,
 'survive': 2457,
 'personality': 1856,
 'crisis': 556,
 'southern': 2346,
 'housewife': 1234,
 'evelyn': 843,
 'couch': 533,
 'ninny': 1734,
 'outgoing': 1800,
 'idgie': 1254,
 'threadgoode': 2523,
 'ruth': 2167,
 'jamison': 1348,
 'experienced': 876,
 'hardship': 1156,
 'whistle': 2744,
 'alabama': 99,
 '1920s': 10,
 'viking': 2686,
 'cusp': 573,
 'manhood': 1549,
 ...}

In [ ]:
len(cv.vocabulary_)

2812

In [ ]:
## text representation ==> tf-idf
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tf = TfidfVectorizer()

In [ ]:
tf.fit_transform(df1["review"])[0].shape

(1, 2812)